### ISSUE TITLE
Steam port switched with Query port

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#103]
_"Each Unturned server uses three consecutive ports while running. The first is used for game traffic, the second for server list queries, and the third for communicating with the Steam backend services."_

I believe this information to be outdated. What can be written/said about these ports to make this information more accurate?

**Comment by SDGNelson** [comment]
Sorry, you are right that this needs to be updated. jatapa submitted #102 which I meant to comment on but forgot during the move. Will comment now.
