### ISSUE TITLE
Suggestion: Would it be good to merge current ItemData with the split off folder portions?

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/U3-Docs#104]
Used ItemData.md for quite a lot of things in modding, I think part of it is considered documentation for the various foldered stuff like Barricades, blueprints, guns, etc.

**Comment by SDGNelson** [comment]
I think Molt has gradually been working on this. @MoltonMontro

**Comment by MoltonMontro** [comment]
@Ongjming

ItemData is being deprecated in favor of separate documentation files per item type. The various documentation in the ItemAsset folder is the official documentation for their respective topics.

**Comment by Ongjming** [comment]
Ok thanks! Sorry for the inconveniences.
