### ISSUE TITLE
Trying to start a server but stuck on (I think) the last step

### ISSUE THREAD

**Issue by Person1809** [SmartlyDressedGames/U3-Docs#116]
I'm trying to set up a Unturned internet server, I have a map, name, password, login token, and ports set. But I keep running my .bat file to try and update it and start it and I keep getting a message saying 'failed to connect to steam servers because k_eresultgsltexpired still retrying' over and over.

**Comment by SDGNelson** [comment]
Fixing the capitalization of k_eresultgsltexpired, according to Steam docs `k_EResultGSLTExpired` means "This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use." Is it an older GSLT re-used from elsewhere? Easiest option might be to generate a new one.
