### ISSUE TITLE
Not loading workshop items and lost connection

### ISSUE THREAD

**Issue by Izzho** [SmartlyDressedGames/U3-Docs#117]
I am trying to run a LAN server and have two issues. 
The first is that I cannot load a curated map:

This server's allowed IP for Workshop downloads: [My IP address]
1257784170 'Bunker Arena' queued for download
1 workshop item(s) to download...
Downloading workshop item: 1257784170
Download workshop item 1257784170 failed, result: k_EResultFail
Unloading 2 Unused Serialized files (Serialized files now loaded: 2)
Attempting to load curated map 'Bunker Arena'? Include its workshop file ID (1257784170) in the WorkshopDownloadConfig.json File_IDs array.
Failed to find map Bunker Arena, defaulting to PEI!

I have tried all of the arenas to no avail. 

The second is, that I can see the server under the LAN category and can join it. After joining it the progress bar does not progress and after approximately ten to twelve seconds the "Lost connection to host or Steam network" comes up and I am disconnected.

So, any help would be appreciated,
Thanks

**Comment by SDGNelson** [comment]
Sorry for the trouble. There have been a couple reports in the last few weeks of the server's workshop files getting into a bad state where Steam simply returns k_EResultFail. In those cases deleting the Servers/ (id) /Workshop/Steam folder caused it to get re-installed and work properly again, hopefully that does the trick here too?

**Comment by Izzho** [comment]
That did work for the k_EResultFail and I can now start and enter a map. I am still getting the failed to find map (name) Arena message and cannot start an arena. Do you need curated maps in the servers/ID/workshop/maps folder?

1257784170 'Bunker Arena' queued for download
1454125991 'Athens Arena' queued for download
2 workshop item(s) to download...
Workshop item found in cache: 1257784170
Installing workshop item: 1257784170
Installed workshop item: 1257784170
Downloading workshop item: 1454125991
Successfully downloaded workshop item: 1454125991
Installing workshop item: 1454125991
Installed workshop item: 1454125991
Unloading 4 Unused Serialized files (Serialized files now loaded: 4)
Attempting to load curated map 'Athens Arena'? Include its workshop file ID (1454125991) in the WorkshopDownloadConfig.json File_IDs array.
Failed to find map Athens Arena, defaulting to PEI!
UnloadTime: 0.073200 ms
Loading level: 8%

**Comment by SDGNelson** [comment]
Glad that you got it downloading! It looks like the actual map name for whatever reason is "Athens Arena Workshop", so if you change the Map command to that is should load.

**Comment by Izzho** [comment]
Great, that did work. As is Unturned, thank you for both.

**Comment by coldun25** [comment]
I faced the same problem too. Deleting the Steam folder did not help, how did you decide? Help me please
