### ISSUE TITLE
Question: Is there a way to add a custom Skill

### ISSUE THREAD

**Issue by BlueBeard63** [SmartlyDressedGames/U3-Docs#120]
Just wondering dont mind if you cannot but if you can how would you add a custom skill to a map for instance Troubleshooting skill? Cause i know that I can do ```new Skill(1, 1, 1, 1);``` through a plugin but im not sure if that will add it to the skills list.

**Comment by SDGNelson** [comment]
Sorry, there is no support for custom skills yet.
