### ISSUE TITLE
Workshop problem on linux

### ISSUE THREAD

**Issue by 0wM** [SmartlyDressedGames/U3-Docs#127]
![neofetch](https://user-images.githubusercontent.com/55652142/152657827-93e11271-3f77-4785-8d35-7b090f80c687.png)

though linux is supported natively, I have to use proton to join this specific server which is called ROEZ. I am sure that this issue has nothing to do with the server itself, as it runs fine on windows (and with proton) but fails to run on linux because of some assets missing for some reason

if I try to join with native linux version of the game, i see this error
![error message](https://user-images.githubusercontent.com/55652142/152657930-4b5140e5-2e35-4597-a5fa-94a2c06fd786.png)

here's a screenshot of me dead, connected via proton
![me dead with proton](https://user-images.githubusercontent.com/55652142/152657988-fb880e2f-6e39-4108-b115-f9adf11330b4.png)

**Comment by SDGNelson** [comment]
Based on the Proton / Linux difference my guess is that somehow it is related to filename case sensitivity. Do you have any control over the problematic mod? (i.e., is it your mod or server?) For example if there is a file path configured like "load cat.png" but the file is actually named "CaT.pNG" it will work in Proton but not Linux.

**Comment by 0wM** [comment]
> Do you have any control over the problematic mod? (i.e., is it your mod or server?)
nope, i am just a player, I tried renaming everything to lowercase by using
`find   -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;`
but didn't have any success with that.
![изображение](https://user-images.githubusercontent.com/55652142/152671589-ae65138f-ffef-4a89-9e85-af4cc2db12ce.png)

I think I found the problem by checking MasterBundle.dat
![изображение](https://user-images.githubusercontent.com/55652142/152671841-49213fa0-c305-4390-94a0-c9832435feb8.png)
After renaming `Asset_Bundle_Name **Roez.masterbundle**` to `Asset_Bundle_Name **roez.masterbundle**` i managed to join, though there's some blur left from custom UI, I guess there are more MasterBundle.dat files to be changed.
![изображение](https://user-images.githubusercontent.com/55652142/152671935-97cf7b9f-9356-495b-8e17-8dcdeb7d01e2.png)

I think I'll contact server admins about that.

**Comment by SDGNelson** [comment]
Nice work! Hopefully they are open to updating the file names.

**Comment by DiFFoZ** [comment]
Thanks! We will fix it as soon as possible.
