### ISSUE TITLE
About not being able to search the server in the server list

### ISSUE THREAD

**Issue by LiangBraun** [SmartlyDressedGames/U3-Docs#131]
Hello! I am a server owner from China, and I am using my home network to build a server. After I edited the server commands, the port of the server is 27089. I have mapped the ports to 27089 and 27090. At the same time, I also filled in the server key, but I still can only enter the server through ip direct connection and cannot enter after searching through the server list.

**Comment by LiangBraun** [comment]
At the same time, I would like to make some suggestions for you to improve the server connection of the game. As a server owner, I believe that many people are fed up with the problem of being DDOSed. I hope you can make an encrypted connection.

**Comment by SDGNelson** [comment]
Sorry for the rouble. Do you have GSLT set? https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GameServerLoginTokens.md

**Comment by LiangBraun** [comment]
yes,i have

**Comment by SDGNelson** [comment]
Does it show in the LAN / history list? If you can attach the Server_ (id) .log file from U3DS/Logs folder there may be a clue. Steam's master server is a black box however so it can be hard to figure out why it is not showing in the internet list.

**Comment by LiangBraun** [comment]
Thank you very much for taking the time to reply to me, I have checked the LAN/History and there is no such server, but I can see it after the IP is directly connected and added to the favorites, I did not see any useful information in the server log

**Comment by LiangBraun** [comment]
Please take a look at my server log if you      https://airportal.cn/190133/FG1dWjDbyn

**Comment by SDGNelson** [comment]
You are right that everything in the log seems fine, so it might be out of both of our control. Since players are able to directly connect it might just start showing up in the internet list once is has some players. (mysterious black box 🤷 )

**Comment by LiangBraun** [comment]
Yes Nielsen, thank you for your answer, you are very responsible and even exceeded my expectations, I hope Chinese game manufacturers can be like you haha

**Comment by SDGNelson** [comment]
Thanks! Sorry not to have a proper answer though. 😞
