### ISSUE TITLE
Can I add my tunneling tool to the docs?

### ISSUE THREAD

**Issue by loriopatrick** [SmartlyDressedGames/U3-Docs#135]
I've created a tool called playit.gg [1] that tunnels connections so people can host game servers at home. I recently got it working with Unturned and created a video [2]. If you're familiar with ngrok it's quite similar but focused on gaming and adds support for UDP and making port ranges public. It's free and supported by custom domain purchases. The program users run on their computer is also open source: https://github.com/playit-cloud/playit-agent.

Would you accept a PR that adds a guide on how to use playit as an alternative to port forwarding?

[1] https://playit.gg
[2] https://youtu.be/Jqmgruvamd4

**Comment by SDGNelson** [comment]
Thanks for creating the Unturned-specific tutorial! I am sorry to say I would be hesitant to directly endorse the third-party project like this (existing external links have been carefully considered). It might make sense to add a list of port forwarding alternatives including playit.gg though. (Thoughts @MoltonMontro?) I will keep it in mind though.

**Comment by MoltonMontro** [comment]
The closest precedent may be something like OpenMod (or the original Rocket). But these are projects that we have worked to officially support/integrate with Unturned to some degree.

playit.gg appears useful, but I think it'd fall out-of-scope of the "official documentation" that we currently cover. I don't believe this is something we should accept a significant PR on at this time (e.g., a dedicated guide/setup page). Similar to how something like the (now defunct) Unturned Server Organiser tool has never been mentioned in these docs.

**Comment by loriopatrick** [comment]
Makes sense. Thanks for the consideration.
