### ISSUE TITLE
Module Reward_#_Auto_Equip bool Does not work for most equippable items!

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/U3-Docs#138]
Hello,

I am currently having issues with the "Reward_#_Auto_Equip" module. While it may work for NPCs, it does not work with the Blueprint_Rewards or Quest_Rewards component. If this was fixed, many, many new things can be implemented to use this system, like custom animations for opening parachutes or eating food in quarters, with you able to continue.

Please fix, and thank you!

**Comment by SDGNelson** [comment]
Sorry, in those cases it is not exactly broken, rather a side effect of how they already handle equipping the next item. As-is it would be a bit hacked together to do special handling for the auto_equip option.
