### ISSUE TITLE
Has_Item NPC Condition doesn't update correctly!

### ISSUE THREAD

**Issue by riflesyste** [SmartlyDressedGames/U3-Docs#145]
Hello,

The visibility Condition modules (the ones that determine whether you can see an NPC/object) do not update correctly with the Has_Item module. Currently, if you are within draw distance of the object and obtain the item that makes it appear, it will simply not appear until you leave the draw distance and reenter. 

I do not know if this is a genuine bug or simply an accepted limitation, but I would be glad if you could find a workaround.

Thank you, Riflesyste.

**Comment by SDGNelson** [comment]
Sorry, this is unlikely to happen anytime soon because it would need a more optimized way to update only the affected objects when the inventory changes. Currently the "has item" check does a search of the inventory.
