### ISSUE TITLE
double handed item

### ISSUE THREAD

**Issue by Bar0nline** [SmartlyDressedGames/U3-Docs#148]
I've been searching for a long time but couldn't find a solution.
**I want my character to hold a knife in both hands.**

https://user-images.githubusercontent.com/80773683/158615853-79112cc5-774a-41b5-aa4c-c7d3fca94670.mp4

**Comment by SDGNelson** [comment]
Sorry, there is not currently a way to attach something to both hands. Ideally at some point there would either be an option to spawn two of the item prefab - one on each hand - or perhaps just a skinned mesh that can be attached to any bone(s).
