### ISSUE TITLE
Can't open batch script.

### ISSUE THREAD

**Issue by ColtoTheHobbit** [SmartlyDressedGames/U3-Docs#15]
I double click the batch script file named "Tutorial.bat", but a popup appears saying "Windows cannot find 'C:\Program'. Make sure you typed the name correctly, and then try again."

**Comment by OX-S** [comment]
i have the same issue, have you fixed it yet?

**Comment by SDGNelson** [comment]
Where do you see `Tutorial.bat`? (If you even see this reply. Sorry it is so late.)
