### ISSUE TITLE
Almost nothing happens when i start steamcmd.exe

### ISSUE THREAD

**Issue by ignskyed** [SmartlyDressedGames/U3-Docs#150]
I don't know if it is normal, but probally it is not. But when i start steamcmd.exe it closes after a couple of seconds, and the only thing that appears is a folder called "logs". This folder contains two files: bootstrap_log.txt and stderr.txt.

Update: Ok, I found the solution. Go to the Local Disk (C:) and create a folder called "steamcmd". In this folder put the file "steamcmd.exe" and run it.

**Comment by SDGNelson** [comment]
Glad to hear you got it working!
