### ISSUE TITLE
Joining The Server

### ISSUE THREAD

**Issue by DerpyCoder21** [SmartlyDressedGames/U3-Docs#151]
I dont know if im and idiot or i didint read enough but i dont know how to join the server.

**Comment by DerpyCoder21** [comment]
nevermind think i got it

**Comment by DerpyCoder21** [comment]
nevermind i still dont got it, please help.

**Comment by SDGNelson** [comment]
Are you hosting your own server and wondering how to join it? Is the server on the same computer, or a different computer? Which operating system are you using?

**Comment by DerpyCoder21** [comment]
im using windows 10, trying to host my own server on my own computer. im confused on how to join it, also how to let freinds play it

>
