### ISSUE TITLE
UnityEvents in config.json do not work!

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/U3-Docs#152]
Hello,

I am hosting a server and I quite need the UnityEvents module to have the ability to turn on. However, they simply do not turn on for some reason. They are all flipped to true, and nothing works. In singleplayer, they all work just the way they are intended to.
![image](https://user-images.githubusercontent.com/66083394/161175776-3388eef3-9109-4561-aae3-ea977b517ccb.png)

Any help would be gladly appreciated.

**Comment by LocoCZ** [comment]
Hello.
I've got the same issue. I tried to create a server, added an NPC which triggers events and an object which has some unityevents on it and nothing happened. However when I switch to singleplayer, it works.

**Comment by SDGNelson** [comment]
My guess is that it is a matter of which events are triggering the other events and whether they are replicated. Can you describe an example setup that is not working as-expected please?

**Comment by DrDallas1** [comment]
Sorry for the late reply. I do not know how Loco structured everything, but this is all my mod hooks.
![image](https://user-images.githubusercontent.com/66083394/161347867-7230888b-0d47-492e-82f5-0aa2e705efce.png)

![image](https://user-images.githubusercontent.com/66083394/161347915-adda0d8f-43a7-4b1e-8582-44b96c1a9421.png)

![image](https://user-images.githubusercontent.com/66083394/161347938-4a58052e-cc87-4cbe-85d1-33ccc4fd35e6.png)

![image](https://user-images.githubusercontent.com/66083394/161347957-eed58ef9-8e9d-4ee5-86d5-28205e9ec8a7.png)

**Comment by SDGNelson** [comment]
It looks like you have NpcGlobalEventHook with AuthorityOnly triggering the ClientTextChatMessenger. Authority only means the event only runs on the server, but client text chat messenger only works from the client. I think you might want ServerTextChatMessenger instead.

**Comment by DrDallas1** [comment]
Okay, will try that!

**Comment by DrDallas1** [comment]
![image](https://user-images.githubusercontent.com/66083394/161351638-bd6d3c35-0d40-4b99-8f39-a0439abcd875.png)

Tried this. Did not work in single player or server.

**Comment by SDGNelson** [comment]
Sorry I should have looked further into your later images: TextChatEventHook is only invoked on the server (& singleplayer), so it cannot be used to replicate the collider to clients. The only currently supported way to reliably replicate the state of an object is using the "binary state" interactable with IOBS event hook.

**Comment by DrDallas1** [comment]
Hmmm. That's quite sad. Would it be possible for you to later add compatibility for all of the different event hooks? There are a lot of different possibilities if people were given the ability to replicate those event hooks to other clients.

**Comment by DrDallas1** [comment]
Hmmmm. I tried using that, with no success. Can you show me the new rewritten "Anastasia" door you added with the recent update? I am not quite understanding how to set up the IOBS event hook.

**Comment by DrDallas1** [comment]
Thank you. Would it be possible for you to document the new updated "Anastasia" door that use the IOBS & Text Chat event hooks? Thanks.

**Comment by DrDallas1** [comment]
Hmmm... interesting. I'll think of a solution to my current issue.

Something I did not understand is how the ClientTextChatMessenger event hook would even work in multiplayer, as in I have never gotten the player to broadcast his message. I think that may be part of a solution I'm thinking of currently... any help appreciated.

**Comment by SDGNelson** [comment]
If you have an event that gets invoked on the client then ClientTextChatMessenger acts as if the local player sent a message. For example using the vehicle turret _Local event would only send the message from the player using the turret.

**Comment by LocoCZ** [comment]
Hey, I was trying to get the IOBS event hook to work. I can't seem to find the issue there, can you see anything that's wrong (I'm standing right above the object so radius doesn't matter)? I also tested random binary hook with npc global hook and that seemed to work in multiplayer.
![image](https://user-images.githubusercontent.com/81763752/161374868-4ef3f07c-68f1-4f2d-84c7-c16d095ec640.png)

**Comment by LocoCZ** [comment]
Here's another example of the Random Binary hook in action. Text chat event hook did not work on it, but worked in singleplayer.

![image](https://user-images.githubusercontent.com/81763752/161375355-4bff38e2-75b3-41ad-93c6-f763b02f9ce4.png)
![image](https://user-images.githubusercontent.com/81763752/161375364-abb643c9-c591-4650-94ab-98e2e4bd03bb.png)


https://user-images.githubusercontent.com/81763752/161375268-2eef2344-e678-431c-8f00-b2fbccef465f.mp4

However if I connect it to an NPC event reward, it works in multiplayer.

**Comment by SDGNelson** [comment]
Do you have the components on the Clip.prefab as well? (Object.prefab is singleplayer and client) Also, you probably only want one BinaryRandomComponent rather than two?

**Comment by LocoCZ** [comment]
Alright so, yeah clip.prefab box collider is assigned in the clip area. Here's what I've done, however it doesn't work in multiplayer. 
![image](https://user-images.githubusercontent.com/81763752/161448077-52c2473a-8932-4211-a613-cb6f95b76ad8.png)
![image](https://user-images.githubusercontent.com/81763752/161448085-787990e5-04cc-4ed8-82a1-74f04e3faae8.png)

Would you be able to give us an example of client text chat & text chat event hook that works in multiplayer please? 

The reason I used BinaryRandomComponent twice before was because I couldn't get the IOBS to work. DrDallas then told me where I was doing a mistake (Interactability Binary_State in .dat)

**Comment by SDGNelson** [comment]
Attached is the converted Anastasia Door, however it does not include dependencies because otherwise Unity would include all scripts in the project. It should work if you already have the Project unity package with the "mod hook" scripts.

[Anastasia Door.zip](https://github.com/SmartlyDressedGames/U3-Docs/files/8410944/Anastasia.Door.zip)

**Comment by LocoCZ** [comment]
I first have to apologize if I'm doing something wrong. After importing the anastasia door, there doesn't seem like anything is inside of the IOBS Event Hook. I even created a new Unity Project and imported project.unitypackage (including mod hooks), then the anastasia door. Is there supposed to be anything inside of that hook? Thank you.
![image](https://user-images.githubusercontent.com/81763752/161621742-6a651b7f-7dd3-4b41-9b5d-526fb3bd0e30.png)

**Comment by SDGNelson** [comment]
Nope that's right - OnStateEnabled and OnStateDisabled are for extending anything the interactable object does not do by default. Playing the animation and sound are handled by default.

**Comment by DrDallas1** [comment]
Okay, I understand now. I sort of got the door to work, sorry for the confusion. Thank you so much for providing insight as to why this could be happening, and especially for giving us the new Anastasia door.
