### ISSUE TITLE
Vulkan on linux

### ISSUE THREAD

**Issue by 0wM** [SmartlyDressedGames/U3-Docs#153]
Using `-force-vulkan` boosts my performance by 20% or so, but there are some issues. The camera movements seem to be "oily" or delayed, like you're playing CSGO with VSync turned on. Also, custom particles in multiplayer are just white squares on Vulkan (I can post a screenshot later).
Here's a small vid showing it: https://www.youtube.com/watch?v=cyYk1o5FZj4 (yes, both look delayed, but vulkan is more delayed)

![settings](https://user-images.githubusercontent.com/55652142/161422513-fcb715d6-d2e3-4922-9a68-b01ffe881950.png)
_settings I used both on OpenGL and Vulkan, no VSync and 1280x1024 professional obliterating resolution_

Will you support Vulkan, or is it a unity problem?

**Comment by SDGNelson** [comment]
Sorry, if I recall correctly Vulkan support in Unity 2019 LTS was not quite 100% yet so it is not enabled in Unturned, but when we update to Unity 2020 LTS later this year I will re-evaluate enabling Vulkan. 👍
