### ISSUE TITLE
Better documentation for "booleans" that are actually evaluated with "data.has"

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#155]
https://github.com/SmartlyDressedGames/U3-Docs/blob/6fc5d8483928fdb20b7287654c621dbdbd1069c8/ItemAsset/Actions.md?plain=1#L16

https://github.com/SmartlyDressedGames/U3-Docs/blob/6fc5d8483928fdb20b7287654c621dbdbd1069c8/ItemAsset/TacticalAsset.md?plain=1#L20-L26

A lot of properties are evaluated based on whether or not they're merely present in the file. Currently, documentation lists these as _booleans_, with no default value listed. Comparatively, actual boolean properties are listed as _booleans_, with a default value listed.

This could be documented better—it's prone to causing confusion.

What's a good term to use for properties that merely need to be declared/present/existent/data.has'd?

Ideally, something that can easily convey how the "data type" works. But if it's not super obvious, we could have a file that lists all non-standard data types (e.g., GUID, ID...) and explains how they work & what they are.

**Comment by SDGNelson** [comment]
Good point. Maybe listing them as a "flag" rather than "bool"? The phrasing "if this flag is present" e.g. "if command line flag -DisableFires is present" seems fairly standard.
