### ISSUE TITLE
Any doc changes needed for Unity 2020?

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#163]
With the recent upgrade from **2019.x** to **2020.3.34f1**, are there any changes that need to be documented for modders wishing to upgrade? A la, [Unity2019.md](https://github.com/SmartlyDressedGames/U3-Docs/blob/77ed9340ea0827f0398fc60da9fae84c7bf409f4/Unity2019.md).

**Comment by SDGNelson** [comment]
As far as I know it has been a smooth transition. There were misc API upgrades and workaround removals I took care of, but when I tested all of the official and curated content it seemed to be fine as-is.
