### ISSUE TITLE
Server is running an older version

### ISSUE THREAD

**Issue by mineges** [SmartlyDressedGames/U3-Docs#166]
![image](https://user-images.githubusercontent.com/37666360/172681207-d091a6c2-c6da-4df4-85d5-d52c39d31e92.png)
Unturned asks me to update the server. Updating it using app_update command in steamcmd.exe does not make any changes.

**Comment by mineges** [comment]
Turns out that server has to be updated using two commands, not one as I thought:

app_update 304930
app_update 1110390

Both commands have to be executed in steamcmd.exe (with admin rights and logging in using "login anonymous" command first), then Steamcmd has to be closed with "quit" command. Server will be updated.

**Comment by SDGNelson** [comment]
You only need to run `app_update 1110390` which is the Dedicated Server AppID (U3DS folder), 304930 is the client (Unturned folder).

**Comment by mineges** [comment]
> You only need to run `app_update 1110390` which is the Dedicated Server AppID (U3DS folder), 304930 is the client (Unturned folder).

Thank you. I have edited my previous reply for convenience.
