### ISSUE TITLE
Latest Version RSS Feed Incorrect

### ISSUE THREAD

**Issue by spookybytes** [SmartlyDressedGames/U3-Docs#167]
The dedicated server update [RSS Feed](https://smartlydressedgames.com/rss/unturned-steam-dedicated-server-updates.xml) missed the 3.22.11.3 update and still shows 3.22.11.2 as the latest version.

**Comment by SDGNelson** [comment]
Sorry about this! I have manually updated it now. Good timing: for the next update I am planning to finally add a better built-in update check.
