### ISSUE TITLE
Can't Add Resource Mod

### ISSUE THREAD

**Issue by Bar0nline** [SmartlyDressedGames/U3-Docs#168]
**Hi, I want to add Resources, but the map does not appear in the editor.**
![unk1nown](https://user-images.githubusercontent.com/80773683/176776791-9db2d073-7f90-40b6-9856-980f0f6cc6aa.png)
![unk2nown](https://user-images.githubusercontent.com/80773683/176776808-47a62640-0638-4fe9-a29f-73d56bf878ed.png)

**Comment by SDGNelson** [comment]
For trees to show up in that list they need a "foliage asset" now, sorry for the hassle: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Foliage.md

**Comment by Bar0nline** [comment]
I managed to add it to the map, but now when I collect the resources, the item does not come to the inventory.

**Comment by Bar0nline** [comment]
ok i got it thanks
