### ISSUE TITLE
New Mod Hook / Script request

### ISSUE THREAD

**Issue by therenaydin** [SmartlyDressedGames/U3-Docs#176]
Hi Nelson, I am not sure if this is the right place for this request but I don't know where to comminucate with you any other.

There are scripts for "Rocket", "Deadzone Volume", "Kill Volume" and even "Landscape Hole Volume". So maybe you can add something called "Water Hole Volume" which removes water inside the box trigger. This would be very helpful for naval mods. If there is already something for this, my bad I didn't know.

**Comment by 0wM** [comment]
it's possible to do with water volumes via devkit, though it's such a pain
![ingame](https://user-images.githubusercontent.com/55652142/184317988-39189bbb-8326-4660-b2b6-03136834cd36.png)
![devkit](https://user-images.githubusercontent.com/55652142/184317994-28bcdb00-7a50-48a0-b2d9-de0a6ecfbfd5.png)

**Comment by therenaydin** [comment]
Thats good so we can fınd its script and use on vehicle mod and stuff. People already been using devkit scripts in their mods, but i didnt see this script so i guess its hidden

**Comment by therenaydin** [comment]
hey uhh i guess i found it inside SDG.Framework.Water there is a WaterVolume script i will try.

**Comment by therenaydin** [comment]
I ripped off WaterVolume script and tried on my mod. Unfortunately we can't remove water. This thing just creates a water and removes its surface. Water is still there.

![image](https://user-images.githubusercontent.com/49097712/184338427-83718462-caf9-4988-9db2-3c8bc3d79aad.png)

```c#
using UnityEngine;

namespace SDG.Framework.Water
{
    public class WaterVolume : MonoBehaviour
    {
        [SerializeField]
        protected bool _isSurfaceVisible;
        [SerializeField]
        protected bool _isReflectionVisible;
        [SerializeField]
        protected bool _isSeaLevel;
    }
}

**Comment by SDGNelson** [comment]
Sorry, the closest would be the "depth mask" trick used by water vehicles like boats that hide the water surface in shallows.

**Comment by therenaydin** [comment]
🥺 thanks

**Comment by therenaydin** [comment]
NELSON you are a chad, I saw todays update you added "Disable Underwater Effects" option. Thanks!
