### ISSUE TITLE
/npcevent command does not work in multiplayer.

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/U3-Docs#180]
Hello,

the /npcevent command broke in some way recently, can't pin with what update exactly. It simply fails to work and dispenses no error when used in multiplayer - I remember it as properly working before. This command is extremely useful for testing and certain things had to exclusively rely on it. Nelson, pls fix.

Thank you, Dallas.

**Comment by SDGNelson** [comment]
Does the server have cheats enabled?

Otherwise nothing should have changed with this command recently. One thing to note is that `/npcevent` does not replicate the event, so it only gets invoked on the server side.

**Comment by DrDallas1** [comment]
Server has cheats enabled, but I guess that can be part of the reason, I guess I assumed that it would replicate the event to clients. Sad that's not possible. Sorry.

**Comment by SDGNelson** [comment]
Considering that NpcEventReward *does* replicate now maybe that should be changed. Will do.
