### ISSUE TITLE
Time of Day properties required for WeatherAsset class

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#181]
https://github.com/SmartlyDressedGames/U3-Docs/blob/abccc95c90885e570df401d5d98e66069435408c/WeatherAsset.md?plain=1#L57

If a WeatherAsset (although not its parent, WeatherAssetBase) doesn't include Dawn/Midday/Dusk/Midnight time of day properties, a vague error is thrown in the in-game error logs. There error is along the lines of `Failed to analyze [path-to-weather.asset]: Object reference not set to an instance of an object`. When looking at the full game logs, some additional context is provided.

![image](https://user-images.githubusercontent.com/7608445/188502207-a2c03b4f-62eb-4ed0-94da-319a6c93fb9c.png)

It seems that at least specifying the time of day properties are required when using the WeatherAsset class, even if the properties are then just set to something unimpactful (e.g., `"Dawn" { "Fog_Color" { "Level_Enum" "SKY_SKY" } }`), or nothing at all (e.g., `Dawn { }`) as a workaround.

Is this requirement intended/necessary? If so, we should update the docs to include a note about this scenario and perhaps have the in-game error message be a bit more helpful. Otherwise, could we have it so that specifying Dawn/Dusk/Midday/Midnight isn't required?

**Comment by SDGNelson** [comment]
True this is not necessary, will change for the next update so those can be left out.
