### ISSUE TITLE
How can I get the textures?

### ISSUE THREAD

**Issue by capjay45** [SmartlyDressedGames/U3-Docs#187]
I would like to customize the textures using the base games official textures as a base but I can't find out how to get them, any tips will be appreciated, thanks.

**Comment by SDGNelson** [comment]
Sorry, they are not currently included in the asset sources package. They are pretty simple though: just 64x64 blobs of color in Gimp.

**Comment by capjay45** [comment]
ah I understand, however will they be included in the future to make modding more accessable for newer modders?

**Comment by capjay45** [comment]
Also is there no possible way for me to obtain the coalition textures? Or maybe you could send them to me because I just wanna turn them red and cant draw accurately. Thanks
