### ISSUE TITLE
Map doesn't upgrade from old foliage to new foliage

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/U3-Docs#19]
Unturned has Ground Upgrader Wizard. I made a map in legacy editor and then decided to upgrade foliage to new for better edit and add new grass in DevKit. After adding materials in tiles map doesn't save and then even doesn't load. 
(stuck in the end of loading). Made everything from this guide because didn't find anything better: https://www.youtube.com/watch?v=gs59TsEZue4&feature=youtu.be

**Comment by SDGNelson** [comment]
Apologies for my delay. I was not monitoring issues on this repository. I followed up on your issue here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1551
