### ISSUE TITLE
[Map Editor Help] A wall of pixels appears in the scope, even when there is nothing in sight 

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/U3-Docs#199]
I am using a custom map. but I found something confusing my vision.
In some areas, when I turn on the scope, there is a wall of pixels in front of me, even though there are no objects in front of me, like this:
1. Confused area, unscoped：
![2](https://user-images.githubusercontent.com/12797737/204094129-3b257995-9574-4789-9cac-935ef1cfcf42.jpg)
2. Confused area, scoped：
![1](https://user-images.githubusercontent.com/12797737/204094177-b221aca0-9c7e-4e38-b0cc-fb7389697418.jpg)
3. Normal area, scoped:
![3](https://user-images.githubusercontent.com/12797737/204094186-8ad72157-d1ac-46a1-8954-70527a1e836a.jpg)
4. when setting `Scope Quality` to Off it is normal
![1jpg](https://user-images.githubusercontent.com/12797737/204202916-1f29d918-ee24-4041-9fa1-e0819f493a19.jpg)

but opened  `Scope Quality`, wall of pixels appears.

Here is the link of the map: [https://steamcommunity.com/sharedfiles/filedetails/?id=2891514820](link), it's a collection.

@MoltonMontro what should I check?

**Comment by MoltonMontro** [comment]
Thanks for linking the map. It doesn't have to do with the position you're in, but with an object in the distance that you're rendering. More accurately, the **Downtown Apartment #3** from the mod with 

Anyways, it's the object called "Downtown Apartment #3" from the Steam Workshop mod with [ID 1935236838](https://steamcommunity.com/sharedfiles/filedetails/?id=1935236838). As a large object, when you're far away it'll switch to a low-detail LOD. This object's lower detail LOD looks like that mess of pixels.

**Comment by makeloffve** [comment]
> Thanks for linking the map/mods – it made it much easier to see what was going on.
> 
> It doesn't have to do with the position you're in, but with an object in the distance that you're rendering. More accurately, the **Downtown Apartment #3** from the Steam Workshop mod called ["City Expansion 2"](https://steamcommunity.com/sharedfiles/filedetails/?id=1935236838). As a large object, when you're far away it'll switch to a low-detail LOD. This object's lower detail LOD looks like that mess of pixels.
> 
> If the mod is still being updated, contact the mod author. Otherwise, don't use that object.

Thanks for your help!
After I removed the object, the problem was solved. and i have reported this issue to the author.
