### ISSUE TITLE
Maps linking to update notes

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#20]
From [3.20.3.0](https://steamcommunity.com/games/304930/announcements/detail/1705114423312944610): "Maps can link to update notes for future curated map updates."

Was this a Config.json setting for maps? If so, we need it added to LevelConfig.md. If not, can we get the "menu visibility" section in CuratedMaps.md updated to explain this?

**Comment by SDGNelson** [comment]
Good point. You are right that it is not part of the level config. I have added a note about it to the curated maps doc.
