### ISSUE TITLE
Server ignores all configurations.

### ISSUE THREAD

**Issue by EvilPasta** [SmartlyDressedGames/U3-Docs#207]
_Good morning my favorite indie developer ^-^_
_Today I ran into a problem, that I couldn't solve by searching online for a solution. So I have made a decision to make it your problem as well, and wrote this public letter to you c:_
_My apologies <3_

**Background:**
I am renting a server. Linux (Ubuntu 20), without any desktop environments. And I connect to it only through ssh. I am using a firewall - firewalld / firewall-cmd, I open ports on game server launch and close them when I stop it (launch scripts).
I have installed Unturned 3 Dedicated Server using the SteamCMD into a custom named folder "Unturned" (that is located in a folder with different game servers).
Oh and I have the steam token for my server, it is being used, the latest use time gets updated. And yes it is technically playable.

**Situation:**
I believe server completely ignores Commands.dat and Config.json in my Servers/MakkaroniServer (my server id) folder.
It keeps using default ports (27015), has no description, a default name, no password, 8 players instead of 2, (PEI map is not a problem yet, but it soon will be).
I managed to play with my friend by opening 27015-27017 ports, thankfully I could change maxplayers while the server was running, and even make myself an admin, but this is not acceptable. I have attempted adding all required stuff to the launch command before the +InternetServer/MakkaroniServer, or simply the port, and I think I even saw "successful Pve" something one time, but in the end no changes. I followed advises regarding making Workshop and Content folders, but that also didn't help.

**At this point I am stuck and I have no idea what to do. :<**

**I also have additional questions:**
- Do I need to open xxxxx port +1, or +2? (example 27015-27016, or 27015-27017) Instructions confused me, so I am still not sure, and keep opening 3 ports. (Actually, Port Forwarding guide says 15-16 is enough, but I am still confused. Can I use a different port, or do I always need certain port open along with the chosen ports)
- Do I need to open both TCP and UDP for such ports? (Port Forwarding guide mention only UDP, so probably I can stop using TCP for Unturned)
- Is it normal, that I see warnings and errors related to shaders and gpu when launching? (it's a server, it doesn't need a gpu >.>)
- Server has crashed twice, each time right after the moment we killed a Mega zombie <.<

Here are the Commands.dat and the launch command from my personal launch script:
.../Unturned/Servers/MakkaroniServer/Commands.dat
```
Name MakkaroniServer
Port 33015
Password <some random password>
Map PEI
Mode normal
Pve
maxplayers 2
```

portion of launchUnturned.sh, with the port as an attribute, but it still doesn't seem to work
```
<...> ./ServerHelper.sh -port/33015 +InternetServer/MakkaroniServer <...>
```

[console_log.txt](https://github.com/SmartlyDressedGames/U3-Docs/files/10314848/console_log.txt)

**Comment by SDGNelson** [comment]
It looks like your Commands.dat file is in the /Servers/MakkaroniServer folder, but the game will create it automatically in /Servers/MakkaroniServer/Server/Commands.dat

**Comment by EvilPasta** [comment]
Somehow I didn't know that Commands.dat was supposed to be in the /Servers/MakkaroniServer/Server/, and so I created it in the MakkaroniServer folder. That's why it didn't work. My own fault, I guess I wasn't attentive enough when reading instructions. Thank you <3
