### ISSUE TITLE
Unturned ask server to configure GSLT even the server is a LanServer

### ISSUE THREAD

**Issue by kj415j45** [SmartlyDressedGames/U3-Docs#210]
As title mentioned, I set up a LanServer on a VPS. When I tried to connect to server, it warns that "Cannot join over the Internet because GSLT is not set". But reading through the documents and I can only find:
> Listing your server on the in-game internet server list requires a [Login Token](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GameServerLoginTokens.md) to be set.

> Note for the server to be visible on the in-game internet server list you will need to set a Game Server Login Token

So the GSLT should NOT be required if I don't want my server to be listed. And obviously, a LanServer should be unlisted.

Anyway, after configuring a GSLT on the server, I could finally connect to the server.

**Comment by SDGNelson** [comment]
It depends on the IP address used to connect to the server. If the LAN server list is used to join it might be getting a public IP address which is on my to-fix list.

**Comment by kj415j45** [comment]
The server is intended to be connected over Internet, however, I don't want it to be listed on the in-game internet server list.  That's why I use `+LanServer/<ServerName>` as parameter. And asked my friends to connect server via VPS's public IP address.  But you said: `It depends on the IP address used to connect to the server. `. Do you mean that GSLT is a Client-side restriction?

**Comment by Buldozeris** [comment]
The whole idea of LAN server is that only your household members could connect to it through the same network. If you are hosting a server - get a token and problem solved. If you don't want other players to connect to your server - use password. Not sure whats the point of hosting a LAN server on VPS?

**Comment by kj415j45** [comment]
> The whole idea of LAN server is that only your household members could connect to it through the same network. If you are hosting a server, get a token and problem solved. If you don't want other players to connect to your server use password. What is the point of hosting a LAN server on VPS?

The point is:
1. The server should not be listed on that list. Even though malicious person could still run a port scanning to find my server's origin IP (and make an attack).
2. GSLT is useless. Or if it's useful, but for what? I don't know if it provides any convenient for developer. But it does somehow increase the difficulty for new player to create their own server due to its configuration method.
3. Password does prevent other player to connect but also add an extra step for my friends to come in. And the player with bad connection quality (both server-side and client-side), they have to repeat this when re-connecting.
