### ISSUE TITLE
Problems with Effect UI

### ISSUE THREAD

**Issue by SteweX** [SmartlyDressedGames/U3-Docs#213]
Hello, i was trying to create test UI, but i have problems with, it's just not displaying.
I've used different versions of Unity, but for now, I'm using this one: 2019.4.11f1

I uploaded my UI to workshop, and put it to server WorkshopDownloadConfig, server & client has successfully installed assets, and put GUID to .dat file, here they are:
Client .dat
<img width="291" alt="image" src="https://user-images.githubusercontent.com/71728819/212445097-7d43c473-98a1-4046-947e-8b12a4bde4f7.png">

Server .dat
<img width="288" alt="image" src="https://user-images.githubusercontent.com/71728819/212445115-882580c6-3d7e-40ac-b5f7-c9c52abde623.png">

Unfortunately it still doesn't work with /effect 32123.

But when i drag .dat file from server to client, it's working, but with nuance:
![image](https://user-images.githubusercontent.com/71728819/212445225-2a0359c5-5a16-4efa-a936-c95f18ca0248.png)

Server just kicks me
![image](https://user-images.githubusercontent.com/71728819/212445255-c16f0344-3246-4f6a-8860-00b4c6e59c60.png)

I also tried using master bundle but even.
I will be very happy if you help me with this problem.

**Comment by DanielWillett** [comment]
If you have the bundles in your game files and in the mod from steam this can sometimes happen (remove it from any subfolders of Unturned/Bundles).
