### ISSUE TITLE
Failed to connect to Steam servers because k_EResultInvalidParam, no longer retrying

### ISSUE THREAD

**Issue by Tragic6** [SmartlyDressedGames/U3-Docs#218]
i need some help if you can contact me on discord or here works my discord{𝓣𝓻𝓪𝓰𝓲𝓬𝓢𝓺𝔀𝓮𝓪𝓴𝓮𝓻#6229}

**Comment by SDGNelson** [comment]
This probably means your Game Server Login Token (GSLT) is invalid.
