### ISSUE TITLE
People can't connect to my server

### ISSUE THREAD

**Issue by NikoEnd** [SmartlyDressedGames/U3-Docs#22]
I have followed all the steps but I cannot get people to connect to my server.
![image](https://user-images.githubusercontent.com/64169948/80035558-85cc5600-84f0-11ea-9c59-b385d4da490d.png)
Here goes my "commands.dat"

**Comment by MoltonMontro** [comment]
Remove the Bind command.

**Comment by NikoEnd** [comment]
I'm probably doing something wrong, I've removed the bind command but people can't get in. With which IP do people have to connect? With my private ip or with my public ip?

**Comment by khakers** [comment]
Other people connect with your public ip, you generally connect with your private ip. If people still aren’t able to get in make sure your port forwarding is all correct.
