### ISSUE TITLE
Unturned Server Internet Protocol

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/U3-Docs#221]
I have some questions that will help me and I'm sure others.

1) Does Unturned Server support IPV6?

> 1.1) If the Server supports IPV6: Is it possible on 1 Server to have 1 IPV4 and 1 IPV6 at the same time?

> 1.2) If the Server supports IPV6: Will it appear in the Servers list?

**Comment by SDGNelson** [comment]
Unturned uses Steam Networking Sockets which do support IPv6, however as-is the game does not work fully with IPv6. All of the older "Steam Matchmaking" library uses IPv4 addresses. Some game code (e.g., IP bans) also don't use IPv6 yet.

**Comment by GabrielMaestre** [comment]
Alright, thanks a lot for the answer!
Just an addition, would it be possible for you to update the libraries (of the game of course) to work 100% with IPV6, I know it can be a little rude or annoying to ask that I apologize but that would cut +90% of DDOS attacks on servers .
(I got to talk to you via email about this last year).

In case it is not possible at the moment, I and the community are very grateful for your work :heart:

**Comment by SDGNelson** [comment]
Thanks! ❤️ Game code *should* gradually have IPv6 support, but I'm not sure if IPv6 is used even with Steam's newer Fake IP feature. Out of curiosity how does IPv6 help with DDOS?

**Comment by GabrielMaestre** [comment]
Glad to hear that, I worked for a short time at an internet provider for internet providers (a little weird) but in general, so far "there is no such thing as an ipv6 attack", generally there aren't enough infected machines to make a strong attack on the Ipv6 protocol, there must be more reasons yes and I will go after the professionals that I worked to give you this answer better. If you want to talk about it, we've already talked about anti data before in the email, even in my profile. Feel free to send a message. Thanks

**Comment by GabrielMaestre** [comment]
https://www.youtube.com/watch?v=786XtFPWfi4&ab_channel=CortesCastDosLoucos%5BOFICIAL%5D (Short BR Vídeo, just caption)

https://phynxfiber.com/blog/ipv6-connectivity-is-a-gamers-dream-come-true/#:~:text=Generally%20speaking%2C%20IPv6%20will%20allow,all%20support%20IPv6%20as%20well

Superficially I can send this, but with a little research you see that there may even be attacks on IPV6 but much less and much weaker too

**Comment by SDGNelson** [comment]
Hm I'll make a note to read up more on IPv6. Maybe I'll see whether it is worth enabling IPv6 on my home network.

**Comment by GabrielMaestre** [comment]
I found an article that is well explained and another advantage of IPV6 it is faster than IPV4

https://blog.servermania.com/ipv4-vs-ipv6/#:~:text=An%20IPv6%20address%20has%20extended,making%20the%20connection%20much%20faster.
