### ISSUE TITLE
Dedicated Server not showing up in "Internet" list

### ISSUE THREAD

**Issue by OldShatterhand8** [SmartlyDressedGames/U3-Docs#223]
The things I've done so far:
Installed the server via steamcmd
Opened ports 27015, 27016 TCP+UDP
Added my GSLT to the config.json
Started the server via ./ServerHelper.sh +InternetServer/MyServer

Now everybody can join the server using the server ip but the server does not show up on the server list nor is it possible to invite people via steam to the server.
Here is the console output I'm getting:

![Git Issue](https://user-images.githubusercontent.com/92958701/220747564-9f1eeef0-4f1d-4b7b-b1a9-0b7fadc283dd.png)

**Comment by OldShatterhand8** [comment]
Also when I look up the GSLT, I see that it is being used since the lastest login in set.

**Comment by SDGNelson** [comment]
It looks like it's starting up okay. When you mention players can join by the server IP: are they on your local network, or over the internet? If they can join over the internet then it should just be a matter of time before it shows up. If by joining through Steam you mean over the internet though it's probably related to the port forwarding configuration.

**Comment by OldShatterhand8** [comment]
Thanks for your reply. Players can also join the server outside the local network. So I think I will just give it some time then. And for the invite via the steam overlay: Does this also only work when the server is listed?

**Comment by SDGNelson** [comment]
Inviting through Steam overlay should work regardless of whether the server is visible on the internet list. What happens when trying to join through the Steam invite?

**Comment by OldShatterhand8** [comment]
When I accept the invite over steam, this happens:
![Unturned Invite Accept](https://user-images.githubusercontent.com/92958701/221063647-4841c674-8135-457a-8cd3-b4412b45c4c2.png)

**Comment by SDGNelson** [comment]
I wonder if it's getting the wrong port through the Steam invite. Off the top of my head there are a few messy things there, but as far as I know the Steam invites should be working normally. I'll double-check whether Steam invites are working on my end.

Could you attach the Client.log file after accepting the Steam invite and then manually connecting please? This way we can see if the port is wrong. https://support.smartlydressedgames.com/hc/en-us/articles/12299037547284

**Comment by OldShatterhand8** [comment]
I found the problem in the log file. So basically what happened was, when trying to connect directly to the server everything was fine. But when trying to connect via steam overlay then my server is sending outward traffic which is somehow sent with a different sender address out of my local network. So when the other is accepting the invite, it is trying to connect to the different sender address where obviously no unturned server is running.
Thanks a lot. Now I know what to fix in my network.

**Comment by SDGNelson** [comment]
Glad to hear you got it sorted out!
