### ISSUE TITLE
Suggestion - Ability to cancel loading into the map editor

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/U3-Docs#224]
I've had it frequently where my map doesn't load. & my FPS counter goes to 2000 FPS. "Indicating" my map failed to load. Only way (I know of) is to alt F4 out & relaunch game. Which can be time consuming if you're trying to fix issues..

**Comment by SDGNelson** [comment]
Ideally it shouldn't be required because regardless of config it *should* be possible to load into the map. Do you have a broken map at the moment? If you can share it to me I can take a look. Closing on here because this is the docs repo.
