### ISSUE TITLE
[Help with Plugin] Detecting player vehicle speed.

### ISSUE THREAD

**Issue by XShine555** [SmartlyDressedGames/U3-Docs#229]
How can I access the speed of the car in KPH as it comes out in the game interface. I have tried with Player.player.movement.getVehicle().speed but converting it to KPH does not show the same speed as the interface.

**Comment by CyberAndrii** [comment]
https://github.com/Unturned-Datamining/Unturned-Datamining/blob/0b24355b1a871d893fe280bab7baed57835e474e/Assembly-CSharp/SDG.Unturned/PlayerLifeUI.cs#L969

**Comment by SDGNelson** [comment]
If I recall correctly the speed is fudged in a few places, in particular using the "input speed" rather than the actual physical speed. In the future I'd like to properly use the physics speed everywhere.

**Comment by XShine555** [comment]
Ops me equivoque de boton perdona. Entonces como puedo obtener la velocidad del coche? Porque en InteractableVehicle solo puedo acceder a physicsSpeed, speed y speedometer y he probado con speed y speedometer pero nada. Y por cierto, ¿tenéis pensado añadir algún evento para cuando se modifique el combustible/velocidad/batería del coche?

**Comment by XShine555** [comment]
Oops I got the wrong button, sorry. So how can I get the speed of the car? Because in InteractableVehicle I can only access physicsSpeed, speed and speedometer and I have tried with speed and speedometer but nothing. And by the way, do you plan to add some event for when the fuel/speed/battery of the car is modified?

**Comment by SDGNelson** [comment]
Approach mentioned by CyberAndrii is probably closest for now. Perhaps events for them someday, but events for frequently-updated values like speed is usually not ideal vs just updated each frame.
