### ISSUE TITLE
Change image color in an effect.

### ISSUE THREAD

**Issue by XShine555** [SmartlyDressedGames/U3-Docs#232]
I recently tried to change the color of an image in an effect to a specific player and I have tried over and over again but the effect doesn't update. What I tried was to take the Image component and change the color to see if it would take effect but it doesn't.

```
EffectManager.sendUIEffect(9999, 55, Provider.findTransportConnection(Player.CSteamID), true);

EffectAsset effectAsset = Assets.find(EAssetType.EFFECT, 9999) as EffectAsset;

GameObject gameObject = Instantiate(effectAsset.effect);

gameObject.transform.GetComponent<Image>().color = Color.red;
```

![Sin título](https://user-images.githubusercontent.com/87085480/224812623-93033c37-c07e-4705-81e4-09c92ef9d112.png)
![image](https://user-images.githubusercontent.com/87085480/224812542-c1f2a778-56af-4136-91ba-5a55fef6d675.png) Not red:(

**Comment by SDGNelson** [comment]
Changing properties directly will only modify them locally, there needs to be an RPC involved for anything to get replicated over the network.

**Comment by XShine555** [comment]
And how can I do it? So far I have tried Provider.sendToClient and some others but nothing.
