### ISSUE TITLE
Server Hosting Rule: Unban

### ISSUE THREAD

**Issue by GabrielMaestre** [SmartlyDressedGames/U3-Docs#233]
Hello how are you?
I read the document along with the Steam links you left.

Example: A player ends up offending another or even the server (moments of rage), and receives a permanent ban, then apologizes publicly on (Discord), and asks to be unbanned.
Could I charge for this?

I understand that it could end up fitting as a micro-transaction, but I'd like to clear that doubt before I do something wrong.    :)

**Comment by SDGNelson** [comment]
Personally I think selling unbans isn't great because it undermines the moderators, however the argument was made that selling unbans is a service fee not a consumable, so selling unbans is allowed under the current rules.
