### ISSUE TITLE
Port-forwarded but ONLY works with Albertino port mapper.

### ISSUE THREAD

**Issue by ciubo22** [SmartlyDressedGames/U3-Docs#24]
I have done everything in the tutorial, i added exception to the firewall too, i tried without exception too, firewall off/on, port-forward is correct too. I still can't open my server for my friends to join (i don't want to use hamachi).
Here are 2 screenshots:
https://prnt.sc/s78gzu
https://prnt.sc/s78g1o

Thanks in advance.
I can use discord/teamviewer if needed.

**Comment by MoltonMontro** [comment]
You said that your port-forward is correct, but you didn't seem to provide any information regarding it. Are you sure that it actually is? Common places where people mess up would be:
- Using the wrong IP address
- Forwarding a port range (one rule for 27015-27017) when their router only supports single port forwards (three rules, one each for 27015, 27016, and 27017)
- Having port forwarding disabled on their router by default

**Comment by ciubo22** [comment]
Here's a ss from my router.
I just said canyouseeme only see the albertino port mapper but not the server.
![image](https://user-images.githubusercontent.com/13187779/80475823-250aa680-8952-11ea-9267-2821b405e7cb.png)
