### ISSUE TITLE
PRs aren't showing Build status

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#243]
When a PR is made, the docs successfully attempt to build that PR. Normally, the result of this build (e.g. failed / passed) would appear in the PR.

**Issue:** PRs are not showing the build status.

Maybe there's insufficient permissions? https://docs.readthedocs.io/en/stable/guides/pull-requests.html#troubleshooting

**Comment by SDGNelson** [comment]
First I double-checked the OAuth permissions, then revoked and re-connected the accounts and re-synced the webhook. I'm not sure what the cause is:

![image](https://user-images.githubusercontent.com/12567645/231565601-f2a4cdcd-ea2b-4444-b066-09be91e71020.png)

**Comment by MoltonMontro** [comment]
Looks good to me (tested with new PR). It's just not retroactive which is fine. https://github.com/SmartlyDressedGames/Unturned-Docs/pull/244

![image](https://user-images.githubusercontent.com/7608445/231571995-1f6ff114-2313-4384-bd33-dce2995037a1.png)
