### ISSUE TITLE
Item Assets that need properties documented

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#248]
Moving this list here. Some of these already have some properties documented, but not all.

- [x] Farm
- [x] Fisher
- [x] Fuel
- [x] Grower
- [x] Melee
- [x] Refill
- [x] Sentry
- [x] Storage
- [x] Structure
- [x] Tank
- [x] Tire
- [x] Tool
- [x] Trap
- [x] Vehicle_Repair_Tool

**Comment by SDGNelson** [comment]
Congratulations on finishing this list!

**Comment by MoltonMontro** [comment]
🥳 Maybe we'll get revised Unity setup instructions eventually too, as part of new docs or as updates to these docs. I think that's the only thing the old Steam Guides are still good for currently
