### ISSUE TITLE
I can not enter data into the terminal after starting the server on Ubuntu

### ISSUE THREAD

**Issue by OnlyChevis** [SmartlyDressedGames/U3-Docs#25]
After starting the server on ubuntu, it is not possible to enter any data into the terminal. Turning off the server is obtained by pressing the key Ctrl + Z. The server is on the VPS/VDS

**Comment by SDGNelson** [comment]
If you add the -ThreadedConsole command-line arg does it work properly? It will become default soon.

**Comment by OnlyChevis** [comment]
Yes. Thank. Everything is working. Remember to add this so that other people do not have questions.
