### ISSUE TITLE
VendorAsset Buying/Selling_#_Amount properties

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#252]
> For [...] Vendor Assets, [...]_Amount condition for specific amounts from stacks (see: Armory Vendor on Liberator) [is missing].

NSTM also pointed this one out. Looks like **Buying_#_Amount** and **Selling_#_Amount** are implemented by different classes?

**Comment by SDGNelson** [comment]
It looks like `_Amount` is not parsed / is not used. I'm not sure what those were for - perhaps the expected min amount of ammo in the item? Currently it requires the amount specified in the item asset.

**Comment by MoltonMontro** [comment]
> It looks like `_Amount` is not parsed / is not used. I'm not sure what those were for - perhaps the expected min amount of ammo in the item? Currently it requires the amount specified in the item asset.

I believe so -- that's how the vanilla Vendors (e.g. Armory vendor) include it in their .dat files. (Lists `1` for basically every item except ammo boxes, where it lists values like `20`.)

```cs
Buying 8
// Highcal military
Buying_0_ID 1192
Buying_0_Amount 20
Buying_0_Cost 40
// Lowcal military
Buying_1_ID 43
Buying_1_Amount 20
Buying_1_Cost 30
// Highcal ranger
Buying_2_ID 1193
Buying_2_Amount 20
Buying_2_Cost 40
// Lowcal ranger
Buying_3_ID 119
Buying_3_Amount 20
Buying_3_Cost 30
// Military magazine
Buying_4_ID 6
Buying_4_Amount 20
Buying_4_Cost 30
// Military drum
Buying_5_ID 17
Buying_5_Amount 20
Buying_5_Cost 30
// Ranger magazine
Buying_6_ID 123
Buying_6_Amount 20
Buying_6_Cost 30
// Ranger drum
Buying_7_ID 125
Buying_7_Amount 20
Buying_7_Cost 30

Selling 3
// Military knife
Selling_0_ID 121
Selling_0_Amount 1
Selling_0_Cost 50
// Binocs
Selling_1_ID 333
Selling_1_Amount 1
Selling_1_Cost 40
// Rangefinder
Selling_2_ID 1008
Selling_2_Amount 1
Selling_2_Cost 600
```

If it's unused and isn't going to be used in the near future, this can be closed / I can close this.
