### ISSUE TITLE
After updating to the new Rocket, it stopped working /Home

### ISSUE THREAD

**Issue by vanya890** [SmartlyDressedGames/U3-Docs#27]

**Comment by SDGNelson** [comment]
Are there any errors or warnings logged when the plugin is loaded?

**Comment by SDGNelson** [comment]
Sorry, I had not realized /home was a built-in command. It looks like Rocket is not considering objects obstruction the bed respawn point. I will fix this for the next patch.

**Comment by vanya890** [comment]
Thank You

вс, 17 мая 2020 г. в 02:06, Nelson Sexton <notifications@github.com>:
