### ISSUE TITLE
Weapon Asset's Enum properties aren't properly explained

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/U3-Docs#270]
https://github.com/SmartlyDressedGames/Unturned-Docs/blob/stable/assets/item-asset/weapon-asset.rst
You could probably assume what these all do, but properties like "Always" vs "Heal" don't fully imply what they'd actually do in-game, and they should probably be explicitly stated anyways.

**Comment by MoltonMontro** [comment]
@Spebby A recent PR adds more information to those properties. Feel free to close this issue.

**Comment by Spebby** [comment]
Aye this is good, closing!
