### ISSUE TITLE
Close older issues not relevant to Documentation

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#279]
Can the older Issues on the repo be closed? Most aren't relevant to the modding/server documentation, and many of them are fairly old anyways.

I skimmed through them, and I think only #58 and maybe #183 are directly relevant to the documentation. The rest looked like troubleshooting or feature requests.

**Comment by SDGNelson** [comment]
Okay: these have now been closed!
