### ISSUE TITLE
Documentation for ObjectAsset properties

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#287]
I believe this is the only remaining asset lacking up-to-date documentation for properties, with the bulk of current object documentation available either from the Update Notes or the [original Steam guide](https://steamcommunity.com/sharedfiles/filedetails/?id=470771210).

I'd like to work through getting these documented for players, but I personally have very little experience with objects. Planning to push a PR at some point, even if incomplete, as I may need to ask you @SDGNelson about some of these properties and their intended use-cases.

**Comment by SDGNelson** [comment]
Wow, that's a big milestone! Yes feel free to check with me about the properties.
