### ISSUE TITLE
The service started but could not connect

### ISSUE THREAD

**Issue by jiaokele** [SmartlyDressedGames/U3-Docs#30]
I set the port 8888
I check through CMD ，The service does not use a port
![image](https://user-images.githubusercontent.com/32627730/85148795-1fab4780-b283-11ea-98ab-3ef124a5ef06.png)

What causes this?

**Comment by jiaokele** [comment]
Request an answer Thank you

**Comment by SDGNelson** [comment]
Off the top of my head there may be some specific port range requirement for the Steam ports. The official recommendation is to use 27015, 27018, 27021, etc for the server ports. I am confident that the port command does work properly because almost all server hosts are using it.
