### ISSUE TITLE
Magazine asset page doesn't mention 'Amount' key.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/U3-Docs#302]
What the title says, someone on the Discord was looking for it but could not find it.

**Comment by Jdance-Media** [comment]
Nevermind, it seems it was included with ItemAsset.

**Comment by MoltonMontro** [comment]
> Nevermind, it seems it was included with ItemAsset.

Yeah – `amount` is part of the ItemAsset class. It's utilized by both magazine assets and supply assets (e.g., ammo boxes) for the # of rounds.

Most of the time if someone can't find a property and the page they're looking at seemingly has everything else, it's probably in a parent class. ItemAsset, ItemWeaponAsset, ItemBagAsset, ItemPlaceableAsset, etc.
