### ISSUE TITLE
When I run the batch file it takes me to my users name in file explorer

### ISSUE THREAD

**Issue by Diamondslayer19** [SmartlyDressedGames/U3-Docs#31]
Im using the internet hosted server and the other files were not created in servers upon launching the batch file

**Comment by SDGNelson** [comment]
Which batch file - the ExampleServer.bat script?

**Comment by Diamondslayer19** [comment]
no, the tutorial.bat, forgot to mention that im also on windows

**Comment by D-AIRY** [comment]
Are you have any whitespace in path to bat file?

**Comment by Diamondslayer19** [comment]
can you explain what you mean more in depth. I understand hardware more than software.

**Comment by D-AIRY** [comment]
Replace `%~dp0ServerHelper.bat` with `"%~dp0ServerHelper.bat"` and try again

**Comment by Diamondslayer19** [comment]
now it says "windows cannot find '+InternetServer/MyServer' make sure you typed the name correctly, and then try again"

**Comment by SDGNelson** [comment]
If you try this does it work?

`start "" "%~dp0ServerHelper.bat" +InternetServer/MyServer`

Good catch @D-AIRY, thanks for raising that issue. I will update the docs and example scripts accordingly.

**Comment by Diamondslayer19** [comment]
nope, it does the same thing as the first problem

**Comment by SDGNelson** [comment]
It takes you to your user directory now, or it says it cannot find something?
Is your script in the same folder as the ExampleServer.bat script? It should be.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open.
