### ISSUE TITLE
Update "Building the Docs" info

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/U3-Docs#327]
Making a note that I should update this info. It's still relatively straightforward, but there's an official Esbonio extension now. Live Preview is now part of this extension, and has been removed from the reStructedText extension. People migrating to the extension may need to manually uninstall Esbonio before reinstalling the extension.

- https://docs.lextudio.com/restructuredtext/articles/preview
- https://docs.esbon.io/en/latest/lsp/howto/migrate-to-v1.html#lsp-v1-migration

**Comment by SDGNelson** [comment]
Exciting quality of life improvements for editing! Thanks for noting to update the building tips.

**Comment by MoltonMontro** [comment]
Added new building info as part of the RTD Addons stuff / deprecation of Sphinx content injection.
