### ISSUE TITLE
Zaupshop unloading

### ISSUE THREAD

**Issue by rubblephp** [SmartlyDressedGames/U3-Docs#332]
![Screenshot_20240518_163047_Chrome.jpg](https://github.com/SmartlyDressedGames/Unturned-Docs/assets/83584625/01674469-2345-4762-bbe3-d8fde15c3f3d)

It gives me this error in a way I don't understand.

**Comment by BlueBeard63** [comment]
Your missing a lib called "System.Drawing"

**Comment by RubbleTV** [comment]
Nasıl kütüphaneyi eklicem

**Comment by rubblephp** [comment]
How do I add the library?

**Comment by BlueBeard63** [comment]
Have you download the lib. If not you can download it from here ([link](https://www.dll-files.com/system.drawing.dll.html)). After that put it in your Rocket>Libraries folder and then restart your server

**Comment by rubblephp** [comment]
Will there be higher versions like 4.7?

**Comment by BlueBeard63** [comment]
The plugin requires the lib to be a minimum of version 4.0.0 and so 4.7 will work

**Comment by rubblephp** [comment]
![Screenshot_20240518_172607_Chrome.jpg](https://github.com/SmartlyDressedGames/Unturned-Docs/assets/83584625/5f38c975-8460-4135-ae39-8867a52dac14)

gave an error like this

**Comment by BlueBeard63** [comment]
That means you haven't given a correct connection string for the plugin to connect into the database

**Comment by rubblephp** [comment]
> That means you haven't given a correct connection string for the plugin to connect into the database 

Okay Thank you for your support, my friend. Let me ask you one more thing. Is there an obligation to create a table when I create a database? Or do they create a table in the database itself?

**Comment by BlueBeard63** [comment]
The plugin will do all the work for dealing with the database all you need to do is add the connection string, you got a dc server I can join?

**Comment by rubblephp** [comment]
send a request to this account 
DC: rubblesoarch

**Comment by SDGNelson** [comment]
Thanks @BlueBeard63 for helping OP!
