### ISSUE TITLE
why is this,cannot be 0.4?

### ISSUE THREAD

**Issue by Gloa233** [SmartlyDressedGames/U3-Docs#343]
![image](https://github.com/SmartlyDressedGames/Unturned-Docs/assets/58651002/cc1d97c2-bcaa-4ea9-bc1d-752356f9ba4c)

**Comment by SDGNelson** [comment]
@MoltonMontro must have been referencing a decompiled version of the game. 😄 Perhaps the question is, is it more accurate to use the actual value from the compiled/decompiled version of the game rather than the source code?

**Comment by MoltonMontro** [comment]
> @MoltonMontro must have been referencing a decompiled version of the game. 😄 Perhaps the question is, is it more accurate to use the actual value from the compiled/decompiled version of the game rather than the source code?

Oh, that's correct – related to: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3083. The difference is fortunately negligible.

**Comment by Gloa233** [comment]
funny fact
