### ISSUE TITLE
Could Unturned add Reward_#_Type Vision?

### ISSUE THREAD

**Issue by Gloa233** [SmartlyDressedGames/U3-Docs#349]

**Comment by MoltonMontro** [comment]
Sorry -- this isn't the proper place to post suggestions. Consider posting on [our forums](https://forum.smartlydressedgames.com/) or in the [Unturned 3.x Community repo's 'Discussions' tab](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions) instead.

**Comment by Gloa233** [comment]
> Sorry -- this isn't the proper place to post suggestions. Consider posting on [our forums](https://forum.smartlydressedgames.com/) or in the [Unturned 3.x Community repo's 'Discussions' tab](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions) instead.
