### ISSUE TITLE
port forwarding not working

### ISSUE THREAD

**Issue by ashitamo** [SmartlyDressedGames/U3-Docs#35]
**A router**
![01](https://user-images.githubusercontent.com/52968572/97100885-5383f700-16d3-11eb-8d47-a8d494b5c025.png)
**B router**
![02](https://user-images.githubusercontent.com/52968572/97100888-5da5f580-16d3-11eb-9fee-7965261f2f27.png)
 
I have two router that "A" is connected to "B".
I had setted three port 27015 27016 27017,but it didnt work.

port 25565 is minecraft server port, and it can work
I just set it ,liking that.
(router B IP:192.168.1.109 and that run in routher A)
**.bat file**
start "" "%~dp0ServerHelper.bat" +InternetServer/Example

My English is terrible,sorry

**Comment by SDGNelson** [comment]
My apologies, I am unfamiliar with a multiple router setup like this. It might not be supported by the Steam GameServer API.

For my curiosity, why do you have two routers?

**Comment by ashitamo** [comment]
because my room in another floor

My home has three floors,setting one router up in second floor.
Another one is setted up in 3F(my room)

**Comment by SDGNelson** [comment]
Oh, interesting way to boost the signal strength.

In the "B router" what is the column to the right of TCP/Both? I notice the Minecraft server has 25565 there, but the Unturned server does not.

Otherwise I am not sure what to suggest, sorry.

**Comment by ashitamo** [comment]
oh... it just is a bug.
it mean "Source IP",i dont know why it is setted.

**Comment by SDGNelson** [comment]
In that case I'm not sure what else to suggest, sorry.

**Comment by ashitamo** [comment]
thank you 👍 
i will close issue
