### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by I3estOFF** [SmartlyDressedGames/U3-Docs#36]
Hello!
I tried to change numbers in config file, because items won't despawn after a while. 
Doesn't work, maybe because all numbers are moved down by one. (screenshot)

Next problem is that weather never changing.
Have you any solution for this problems?

[
![screen](https://user-images.githubusercontent.com/63112899/97931051-1c65b380-1d6d-11eb-8f69-d9bb587c47f2.png)
](url)

**Comment by SDGNelson** [comment]
The config has a separate section for easy, normal, and hard mode (not ideal admittedly) - are you sure you are editing the same section as the server's difficulty?

**Comment by I3estOFF** [comment]
Yes im sure, server level is set to normal and im editing ,,normal" section in config, that what u can see on the screenshot.

And i don't see anything about weather in config maybe thats a problem of second issue.

To spawn items in buildings i need to restart server. Weather isn't changing automactly, i can do this only by command

**Comment by SDGNelson** [comment]
Hmm... I will check into the down-by-one config display thing.

**Comment by MoltonMontro** [comment]
I believe you resolved this issue in November of last year. Could we close this @SDGNelson?

**Comment by SDGNelson** [comment]
Yeah, feel free to comment and I will re-open.
