### ISSUE TITLE
Can't input commands in linux?

### ISSUE THREAD

**Issue by y1meng** [SmartlyDressedGames/U3-Docs#37]
![image](https://user-images.githubusercontent.com/45099938/98458623-c7db9180-21cd-11eb-8b3a-e382b75a1718.png)

**Comment by SDGNelson** [comment]
It looks like one of the times it worked, but the others times not. Perhaps there is a character before/after your input? I should update the '?' message - it was in the initial implementation in 2014 and probably intended to be changed

**Comment by y1meng** [comment]
> It looks like one of the times it worked, but the others times not. Perhaps there is a character before/after your input? I should update the '?' message - it was in the initial implementation in 2014 and probably intended to be changed

I solved this problem by installing OpenMod, thank you
