### ISSUE TITLE
I can't get onto any servers because it says that my game doesn't trust the encryption.

### ISSUE THREAD

**Issue by y1meng** [SmartlyDressedGames/U3-Docs#38]
Is there a solution?

**Comment by y1meng** [comment]
![image](https://user-images.githubusercontent.com/45099938/98696506-d92fc400-23ae-11eb-95b9-3b5e83f59d69.png)

**Comment by SDGNelson** [comment]
If you can attach the Client.log file I can double-check the exact reason:

1. Right-click Unturned in your Steam Library
2. Select Properties > Local Files > Browse Local Files
3. Attach Client.log file from the Logs folder

Most likely however it is an issue with certificate expiry which has been reported to Valve, so hopefully we will hear back soon.

**Comment by y1meng** [comment]
> If you can attach the Client.log file I can double-check the exact reason:
> 
> 1. Right-click Unturned in your Steam Library
> 2. Select Properties > Local Files > Browse Local Files
> 3. Attach Client.log file from the Logs folder
> 
> Most likely however it is an issue with certificate expiry which has been reported to Valve, so hopefully we will hear back soon.

[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/5524033/Client.log)
Tonight found that it has returned to normal, but I still uploaded the log

**Comment by SDGNelson** [comment]
Glad to hear that it was working again for you. In that case it must have been the certificate expiry issue.
