### ISSUE TITLE
Cant Download Mods

### ISSUE THREAD

**Issue by SuperHurley** [SmartlyDressedGames/U3-Docs#40]
When I I try to do the Correct way to install the mods it doesn't work and responds with  k_EResultNoMatch this is the newest version.

**Comment by SDGNelson** [comment]
Perhaps the file ID is wrong? (judging from "no match" error)

**Comment by SuperHurley** [comment]
It shouldnt all the ids work on single player I copied it form the workshop

**Comment by MoltonMontro** [comment]
> It shouldn't all the ids work on single player I copied it from the workshop, plus when I used the non-dedicated server it worked

Just for reference, could you attach (or copy-paste into a `code box` \`code box\`) the contents of your **WorkshopDownloadConfig.json** file?

**Comment by SuperHurley** [comment]
> > It shouldn't all the ids work on single player I copied it from the workshop, plus when I used the non-dedicated server it worked
> 
> Just for reference, could you attach (or copy-paste into a `code box` `code box`) the contents of your **WorkshopDownloadConfig.json** file?

`{
  "File_IDs": [
    633172336,
    727393259,
    758826029,
    918295729,
    928394140,
    1166562219,
    1232252658,
    1632229027,
    1647986053,
    1670772374,
    1687818959,
    1688319209,
    1702240229,
    1727733956,
    1727765824,
    1753131903,
    1767554683,
    1770820566,
    1804433423,
    1868775434,
    1959614756,
    1963788619,
    1963790065,
    1965934095,
    1975500516,
    1979157694,
    2026753123,
    2079953791,
    2082764297,
    2088862222,
    2093259736,
    2134208150,
    2136562988,
    2152811193,
    2165158841,
    2183598175,
    2183604366,
    2183611032,
    2189038676,
    2193789780,
    2195430853,
    2202393257,
    2229881159,
    2232068109,
    2235248970,
    2235585190
  ],
  "Ignore_Children_File_IDs": [],
  "Query_Cache_Max_Age_Seconds": 600,
  "Max_Query_Retries": 2,
  "Use_Cached_Downloads": true,
  "Should_Monitor_Updates": true,
  "Shutdown_Update_Detected_Timer": 600,
  "Shutdown_Update_Detected_Message": "Workshop file update detected, shutdown in: {0}",
  "Shutdown_Kick_Message": "Shutdown for Workshop file update."
}`

**Comment by SDGNelson** [comment]
That is a lot of IDs! Okay, in that case if you can attach steamcmd/logs/workshop_log.txt it should have logged which particular item has no match.

**Comment by SuperHurley** [comment]
ok I found the file, but it says this Error `Wrong AppID 304930 in workshop item details`

**Comment by SDGNelson** [comment]
It says that for all of the files? Hmm... I have not seen that before, but my guess is that locally it thinks the dedicated server is not Unturned (304930). The dedicated server has a separate appid (1110390), but should be allowed to use Unturned workshop files. Maybe run steamcmd validate to force it to fetch the latest app configuration?

**Comment by SuperHurley** [comment]
hmm still doesn't seem to be working

**Comment by SDGNelson** [comment]
Sorry, I am not sure what else to suggest then. I assume you are doing a regular install using steamcmd and the dedicated server? i.e. not editing steam_appid.txt, using client files, or other weird shenanigans?

**Comment by SuperHurley** [comment]
yes only steam install

**Comment by SuperHurley** [comment]
one interesting thing is that the france map was able to install

**Comment by MoltonMontro** [comment]
> hmm still doesn't seem to be working

I was also unable to recreate your issue on my Windows 10 device, with a SteamCMD setup of the U3DS dedicated server app, and the same WorkshopDownloadConfig.json contents as you had provided. The worst issue I ran into were a few mods having errors from being, e.g., not compatible with the latest version of the game. Toxicity Mega Locker being an obvious example, as it hasn't been updated in years.

You may want to consider manually removing all mods from the file, and only adding a couple IDs at a time, until you re-add all of your desired mods, and hopefully resolve the problem somewhere (perhaps, _somewheres_) along the way.

**Comment by SuperHurley** [comment]
I uninstalled and reinstalled and its still not working

**Comment by SDGNelson** [comment]
I think Molt was referring to uninstalling the workshop files and trying a few at a time, rather than reinstalling the server itself.

**Comment by SuperHurley** [comment]
well this isn't really a fix but I was able to make it work by transferring files to the dedicated server
