### ISSUE TITLE
Network authentication issue?

### ISSUE THREAD

**Issue by Ultrover** [SmartlyDressedGames/U3-Docs#43]
https://gyazo.com/b698af97831ff55e14f09b27a6241a27 Can you fix this?

**Comment by Ultrover** [comment]
Whenever I try to join the server it kicks me off and gives me this message

**Comment by SDGNelson** [comment]
If you can attach this file there may be more details:
1. Right-click Unturned in your Steam Library
2. Select Properties... > Local Files > Browse...
3. Open the Logs folder
4. Attach the Client.log file to your reply

**Comment by Ultrover** [comment]
[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/5928834/Client.log)

**Comment by SDGNelson** [comment]
It looks like this log was from partway through loading into the main menu. It gets emptied each time the game is restarted so, could you attach the log after you get the error again please?

**Comment by Ultrover** [comment]
[Client.log](https://github.com/SmartlyDressedGames/U3-Docs/files/6461373/Client.log)

**Comment by Ultrover** [comment]
This time I closed unturned after now getting a new error "You do not have the map this server uses"

**Comment by Ultrover** [comment]
Sorry for not responding. I fixed it. I just deleted the unturned folder and reinstalled the game.

**Comment by SDGNelson** [comment]
No worries, glad to hear you got it working.
