### ISSUE TITLE
Getting Kicked After Doing a Command

### ISSUE THREAD

**Issue by BlueBeard63** [SmartlyDressedGames/U3-Docs#46]
![image](https://user-images.githubusercontent.com/49408282/109337118-3e270100-785c-11eb-922c-131f1366e03e.png)

**Comment by PandahutMiku** [comment]
This is plugin related, seems some plugins need to re-compile after the update, some SteamPacker methods got changed and such.

**Comment by BlueBeard63** [comment]
K ty
