### ISSUE TITLE
Having a very difficult time installing Rocket.

### ISSUE THREAD

**Issue by Thesinofthetin** [SmartlyDressedGames/U3-Docs#47]
I am running Ubuntu Server 20.4 LTS using your official documentation to setup my vanilla server.  I have it successfully setup.  Now I want to install rocket.  I wget the LDM port of rocket and copied the Rocket.Unturned into the Modules folder of my server.  Then I startup the server.  No rocket folder is made and I am pulling my hair out.  I just need the auto saving feature.

**Comment by SDGNelson** [comment]
By "wget" do you mean you are cloning the source from GitHub? The easiest solution would be to copy the Rocket.Unturned folder from Bundles/Extras into the Modules folder, otherwise you would need to compile the code.

**Comment by Thesinofthetin** [comment]
I didn't see the rocket.unturned folder in the extras folder.

**Comment by SDGNelson** [comment]
Did installing from there do the trick for you? More details in the installation docs: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Rocket.md

**Comment by aman7** [comment]
![rocketlocation](https://user-images.githubusercontent.com/6502438/111051397-b30f5300-8478-11eb-9618-0086bced6a98.png)
its here

**Comment by Thesinofthetin** [comment]
> Did installing from there do the trick for you? More details in the installation docs: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Rocket.md

I just scratched linux all together and moved to windows for my server.  Everything has been working great since then.  Now the real challenge is finding compatible plugins.

**Comment by SDGNelson** [comment]
Glad to hear that you sorted things out in the end!
