### ISSUE TITLE
connection already dead

### ISSUE THREAD

**Issue by ericmao0910** [SmartlyDressedGames/U3-Docs#48]
i just download Unturned dedicated server and i cant even join my own server.
server got this message:
connection already dead (0 4003 Cert is not authorized for appid 1110390, only 304930)
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp(2473) : Assertion Failed : [#2615299963 UDP steamid:***@***]problem(4003) %s, but connection already dead (0 4003 Cert is not authorized for appid 1110390, only 304930)
src\steamnetworkingsockets\clientlib steamnetworkingsockets_udp.cpp(1231) : Assertion Failed: Getstate() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally
src\steamnetworkingsockets\clientlib steamnetworkingsockets_udp.cpp(1231) : Assertion Failed: Getstate() == k_ESteamNetworkingConnectionState_ProblemDetectedLocally

can you help me?

**Comment by SDGNelson** [comment]
Recently this has been popping up occasionally. Yesterday it happened on my test server and for some reason steam_appid.txt was 1110390. If you open U3DS/steam_appid.txt does it say 304930? (it should) This file is included in the Steam download, but I think I might change the game to write it before initializing Steam.

**Comment by ericmao0910** [comment]
@SDGNelson my steam_appid.txt said "1110390". i change that to 304930, and the server works.Thanks! and i enjoy U4. hope you work perfectly!

**Comment by SDGNelson** [comment]
Thanks, glad to hear that did the trick! I will make the game override that with the correct value in this coming week's update.
