### ISSUE TITLE
Adminlist.dat

### ISSUE THREAD

**Issue by Christopher111111111** [SmartlyDressedGames/U3-Docs#50]
I am, again, in need of help. I am sorry if it is in plain sight like last time but I cannot seem to make myself admin and am unable to do cheats, an it sends it into the chat instead of giving me the item.

**Comment by aman7** [comment]
in the server's console write admin <yourSteamID>
and if you are in server, just write admin yourNick

**Comment by Christopher111111111** [comment]
Thank you, I was trying to do "/admin" and "@admin".
