### ISSUE TITLE
steam_appid.txt is wrong

### ISSUE THREAD

**Issue by ericmao0910** [SmartlyDressedGames/U3-Docs#53]
Hi!me again. Last time i just change steam_appid.txt to 304930 and the server works. But now it didnt, because this file will check automatically and change that to 1110390 and the the problem will still be contain.Please fix it. Thanks!

**Comment by SDGNelson** [comment]
As mentioned in my reply to your original issue (#48) the game will override that file with the proper value in this week's Friday update.
