### ISSUE TITLE
Server not using UDP port?

### ISSUE THREAD

**Issue by RealDoesStuff** [SmartlyDressedGames/U3-Docs#63]
This has left me confused and frustrated for the past... 3 hours. I'm not sure what to do now cause I have tried mostly everything I can think about.

(port forwarded ports 27015-27017 on TCP and UDP)
![image](https://user-images.githubusercontent.com/84999417/120052269-d15a0900-bffa-11eb-802e-07e2e5b22904.png)
(netstat for unturned dedicated server process)

Used same ports with Source Dedicated Server just fine. (currently offline for unturned)

Seems to be an U3DS problem since I have used the previous client shortcut method in the past just fine.

**Comment by SDGNelson** [comment]
What happens when you actually try to connect to the server?

Sorry I am not familiar with netstat, but I imagine one potential reason could be if Steam Networking Sockets is not using the Windows socket APIs.

**Comment by RealDoesStuff** [comment]
I myself am able to connect successfully. My friends cannot though.

I believe the server seems to connect to Steam.

**Comment by SDGNelson** [comment]
In your .bat script are you using +LanServer? If so, changing it to +InternetServer will open it to the internet.

**Comment by RealDoesStuff** [comment]
Can confirm I was using +InternetServer

**Comment by SDGNelson** [comment]
In that case it is hard for me to troubleshoot because it is probably something in the port forwarding or firewall setup, sorry. If you attach the Logs/Server_ (id) .log file there might be some networking-related error, but since you can connect locally just fine the most likely cause is network configuration.

**Comment by RealDoesStuff** [comment]
Firewalls were ready for the connection, and I tried DMZ as well. I'll provide a log file when possible.

**Comment by RealDoesStuff** [comment]
I can't host servers anymore except for P2P.
This is cause I am now using the Starlink network. Thanks for the trying to help my issue! -RdS
