### ISSUE TITLE
Keeping stuff on the characters

### ISSUE THREAD

**Issue by OsKa322** [SmartlyDressedGames/U3-Docs#66]
Hi, i have like 2k hours in Unturned and always been nervous about those people who log off with their stuff. Can u do something like rust has ? I mean, when someone is logged off u can still kill him and he's just sleeping. Becouse i on servers i use a lot of c4's and can't even reach the main loot becouse it is on the characters.

**Comment by SDGNelson** [comment]
Eventually perhaps, but not in the near future. There is a server option to prevent using multiple characters which can help prevent this.

**Comment by OsKa322** [comment]
Yea but u still has an option to keep stuff on your primary character

pt., 11 cze 2021, 21:46 użytkownik Nelson Sexton ***@***.***>
napisał:
