### ISSUE TITLE
Bolt action gun does not play hammer animation in multiplayer!

### ISSUE THREAD

**Issue by kotyaraaa** [SmartlyDressedGames/U3-Docs#69]
I made gun with custom projectile and added "Action Bolt" line into its .dat file. This weapon works perfectly in singleplayer. But hammer animation is not played after shooting in first person cam on the server. Here is video where i tested this gun with my friend. You can hear hammer sound from him (animation is played). But hammer animation does not want to be played on my hands!

I have tested vanilla rocket launcher (using modded magazine with 3 shots and "Action Bolt" line) and found the same problem.

https://user-images.githubusercontent.com/85970851/122136883-14fea080-ce4c-11eb-8a08-919d92dfddc2.mp4

**Comment by SDGNelson** [comment]
Closing because you opened a duplicate issue in the other repo, replied there.
