### ISSUE TITLE
NPC Global Event Hook Documentation?

### ISSUE THREAD

**Issue by AndrewGrafics** [SmartlyDressedGames/U3-Docs#79]
I'm extremely curious on how this works, if you can write a quick description or explanation to what it is, that would be awesome. Thanks!

**Comment by SDGNelson** [comment]
There is a brief description here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ModHooks.md#npc-global-event-hook

Here is the NPC Reward_Type doc Molt added recently: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/NPCAsset/Rewards.md#event

I will make a note to add a link between those two in the documentation.
