### ISSUE TITLE
I just want to play with friends

### ISSUE THREAD

**Issue by tiredman1** [SmartlyDressedGames/U3-Docs#86]
I wanted to play unturned with a friend and so look up a video how to do it. Got this  "3.21.25.1
Hosting dedicated servers using client files has been deprecated since June 2019.
Please use the standalone dedicated server app ID 1110390 available through SteamCMD instead.
For more information and an installation guide read more at:
https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md" so I followed the link to a website downloaded what it said to download and followed the video. Im getting the same error. What am I doing wrong?

**Comment by SDGNelson** [comment]
Sorry for the trouble. Did you follow the steps in the guide to download the steamcmd version of the Unturned server? The message you mentioned happens when trying to run the regular game as a server through Steam.

**Comment by tiredman1** [comment]
Downloaded the steamcmd like the video said and followed the video. Is there more to the installation? (Besides obviously following the video)

**Comment by SDGNelson** [comment]
How far did you get following the video? It should have installed a folder named "U3DS" with the dedicated server files.

**Comment by tiredman1** [comment]
Followed the whole thing but thought the U3DS I could just do my unturned file. I'll search for that today

**Comment by tiredman1** [comment]
Ok found it and it got rid of the problem. If I have anymore questions ill let you know! but out of curiosity why isn't there just a play with friends option in the game without having to make a server? (just curious if there was a reason not to have that)

**Comment by tiredman1** [comment]
Alright I found it. Thank you if I got anymore more problems I'll reach out. Thank you! Have a good day

**Comment by SDGNelson** [comment]
Glad to hear you got it working!
